### ISSUE TITLE
Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by spanjaan** [wintercms/wn-workshop-theme#1] opened 2022-07-18 10:19 UTC
When i running this command **"php artisan mix:compile -p theme-workshop"** 
Mixing package "theme-workshop"

This error shows me.
**"In Filesystem.php line 187:
                                                                                                                                                        file_put_contents(C:\xampp\htdocs\winter-new\C:\xampp\htdocs\winter-new\themes\workshop/mix.webpack.js): Failed to open stream: No such file or directory "**                                                                                                                                                 

How to solve this? please help me.

**Comment by RomainMazB** [comment] 2022-07-18 10:51
Hi,
Please provide the full error stack trace so we can investigate further.

**Comment by damsfx** [comment] 2022-07-18 11:52
@Anjaan2077 are you in a Windows environment!?  
If so, your issue may be related to https://github.com/wintercms/winter/issues/505

**Comment by spanjaan** [comment] 2022-07-18 15:07
@damsfx i tried to change provided classes but did not work.
still shows me error again.
**C:\xampp\htdocs\wintermodify>php artisan mix:compile -p theme-workshop
Mixing package "theme-workshop"
Unable to compile package "theme-workshop"**

**Comment by spanjaan** [comment] 2022-07-18 15:13
@RomainMazB Hi,
i am running in windows machine, i just install workshop theme and compile them but shows me following error . my wintercms is default configuration.
i am run this command
**"php artisan mix:compile -p theme-workshop"**
shows me this error.
**"In Filesystem.php line 187:
file_put_contents(C:\xampp\htdocs\winter-new\C:\xampp\htdocs\winter-new\themes\workshop/mix.webpack.js): Failed to open stream: No such file or directory "**
i haven't any idea solve this problem.

**Comment by LukeTowers** [comment] 2022-07-19 06:09
Duplicate of https://github.com/wintercms/winter/issues/505

**Closed as completed by LukeTowers** 2022-07-19 06:09 UTC
